---
- name: remote copy
  hosts: all
  become: yes
  tasks:
    - name: fetch
      ansible.builtin.fetch:
        src: /var/www/html/*
        dest: /var/www/html1/
        flat: yes

    - name: copy
      fetch:
        src: /var/www/html1/*
        dest: /var/www/html/
        recursive: yes


