---
- name: SCP
  hosts: all
  vars_prompt:
    - name: Source_file
      prompt: Source_file
      private: no
    - name: Destination
      prompt: Destination
      private: no
    - name: mode
      prompt: file_permission
      private: no
  tasks: 
  - name: copy from local to remote
    copy:
      src: '{{ Source_file }}'
      dest: '{{ Destination }}'
      mode: '{{ mode }}'
    register: scp

  - debug:
      var: scp
