---
- name: INSTALLING WEB SERVICE PACKAGE  
  hosts: all
  become:  yes
  vars_prompt:
    - name: PACKAGE
      prompt: "Enter name of your Package:"
      private: no

    - name: URL
      prompt: "Enter URL:"
      private: no
      
  tasks: 
    - name: INSTALL PACKAGE 
      yum:
        name: '{{ PACKAGE }}'
        state: latest
    
    - name: SERVICE START
      service: 
        name: '{{ PACKAGE }}'
        state: started
        enabled: yes

    - name: STATUS
      shell: service '{{ PACKAGE }}' status
      register: STATUS

    - debug: 
        var: STATUS

    - name: Package
      when: PACKAGE ==  'httpd'
      notify:
        httpd

    - name: Package
      when: PACKAGE ==  'nginx'
      notify:
        nginx

  handlers:
    - name: httpd
      get_url:
        url: '{{ URL }}'
        dest: /var/www/html
        mode: 0755

    - name: nginx
      get_url:
        url: '{{ URL }}'
        dest: /usr/share/nginx/html
        mode: 0755
  tasks:
    - name: SERVICE START
      service:
        name: '{{ PACKAGE }}'
        state: reloaded


          # - name: UNZIP THE FILE
      #     shell: unzip /var/www/html/*zip -d /var/www/html/
